version: '3.7'

services:
  node:
    build: .
    depends_on: 
      - mysql
    ports:
      - 3000:3000
    volumes:
      - .:/app/
      - /app/node_modules
    command: npm run dev

  mysql:
    image: mysql:5.7
    environment: 
      MYSQL_DATABASE: tapit
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./.data/:/var/lib/mysql